### ISSUE TITLE
Make AbstractMicroserviceHttpRepository accepting a criteria

### ISSUE THREAD

**Issue by mtarld** [mtarld/api-platform-ms-bundle#34]
`findOneBy` and `findBy`methods only handle one property. 

They need to be able to handle the whole criteria, passed as an array.

We need to be careful about BC breaks and trigger a deprecation when the end-user is calling these methods without a criteria

**Comment by ismail1432** [comment]
There is already a `$additionalQueryParams` that accept an array and transform this array into query string with `buildUri`
It's not enough ?

**Comment by mtarld** [comment]
Indeed this could be a valid workaround, but IMHO it doesn't make any sense.

For example, if you search the second page of products with "foo" name and "bar" category.
Right now you should write something like that:
```php
$repo->findBy('name', 'foo', [
    'category' => 'bar',
    'page' => 2
]);
```
As you can see, criteria and pagination are mixed.

As a developer using that lib, I'd rather like to write:
```php
$repo->findBy([
   'name' => 'foo',
   'category' => 'bar'
], [
    'page' => 2,
]);
```

WDYT?

**Comment by mtarld** [comment]
I've created a PR implementing that feature. 

Let me know what do you think about it! :slightly_smiling_face:

**Comment by mtarld** [comment]
As discussed together, it's ok then!
