### ISSUE TITLE
Deal with access token

### ISSUE THREAD

**Issue by ismail1432** [mtarld/api-platform-ms-bundle#35]
Many API are accessible only with an access token, we can improve `HTTP client wrappers` to add a way to retrieve (create) an access token and pass it in the request.

We can have a default AccessTokenCreator helper that can be use by default and configured via the config and we can let the possibility to register a CustomAccessTokenCreator with an interface

```php
interface AccessTokenCreatorInterface
getAccessToken()

class DefaultAcessTokenCreator implements AccessTokenCreatorInterface
// configured form config file

class CustomAccessTokenCreator implements AccessTokenCreatorInterface
// Logic implemented by the end user

AbstractMicroserviceHttpRepository::request() 
{
  if($this->accessTokenCreator !== null)
   {
      $this->accessTokenCreator->getAccessToken()
      // pass it into header
}
```
[Edit] :warning: 
Since we deal with tag and autoconfiguration, The AccessTokenCreator helpers have to implement `AccessTokenCreatorInterface` and they can also deal with the priority :tada:

**Comment by mtarld** [comment]
That's a great idea, this indeed could be injected in the `GenericHttpClient`.
Moreover, there are plenty of authentication ways (Basic Auth, Bearer, OAuth, ...).
Therefore IMHO, the AccessTokenCreatorInterface should have a method that returns the access token as a string but also another method that returns the relevant header.

WDYT?

**Comment by ismail1432** [comment]
I do agree :100:
