### ISSUE TITLE
Replace the serialization of the body with json httpclient option

### ISSUE THREAD

**Issue by ismail1432** [mtarld/api-platform-ms-bundle#46]
In GenericHttpClient, The body is serialized with the format defined in the microservice configuration.

I suggest to remove this and let the json option of httpclient transform the body.

If we do this we can remove the serialiazer dependence 

Wdyt?

**Comment by mtarld** [comment]
The serialization format could be anything depending on the configuration. It could be JSON, JSON-LD, or even CSV.
I'm afraid that we can't delegate deserialization to the `ResponseInterface::json` method here.
