### ISSUE TITLE
Error on installation during clear:cache

### ISSUE THREAD

**Issue by ismail1432** [mtarld/api-platform-ms-bundle#50]
Hello 

I have an issue when I run `composer require mtarld/api-platform-ms-bundle`

output :

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 222:
!!                                                                         
!!    The child config "name" under "api_platform_ms" must be configured.  
```

Maybe we should load a default configuration to avoid this

**Comment by mtarld** [comment]
Actually, it's because the recipe is missing in https://github.com/symfony/recipes-contrib
We should submit a PR on that repository to add the recipe

**Comment by mtarld** [comment]
Here is the related PR: https://github.com/symfony/recipes-contrib/pull/1102
