### ISSUE TITLE
Support for Symfony 6

### ISSUE THREAD

**Issue by art-cg** [mtarld/api-platform-ms-bundle#61]
Hi,

are there any plans for Symfony 6?
I started to work on a PR for this.
But i will pause until api-platform 2.7 or 3.0 is released (maybe this month?). There are to many errors from APIP 2.6.6

Maybe a major release with PHP >= 8 and Support for Symfony 4.4, 5.3 and 6.0 and APIP 2.7 and 3.x ?
https://symfony.com/releases

Greetz

**Comment by Chris53897** [comment]
https://github.com/api-platform/core/issues/4543

**Comment by Chris53897** [comment]
@mtarld 
After that Blocker by APIP/Core is gone with 2.6.7 and this is merged https://github.com/mtarld/api-platform-ms-bundle/pull/67 i can work on Symfony 6 Support.
