### ISSUE TITLE
AbstractMicroserviceHttpRepository::delete status code wrongly handled

### ISSUE THREAD

**Issue by mtarld** [mtarld/api-platform-ms-bundle#63]
The `AbstractMicroserviceHttpRepository::delete` is dealing with the status code in the wrong way.
< 500, < 400, [...] is in the wrong order IMHO. We'll always have a server exception no matter the status code value.

We must update that and add related tests.

**Comment by ismail1432** [comment]
👋 Sorry I don't get what do you mean by "wrong order" and "We'll always have a server exception"?

**Comment by mtarld** [comment]
Sorry if I wasn't clear enough ^^
Here is a part of the `delete` method:
```php
$response = $this->request('DELETE', $this->buildUri($iri, $additionalQueryParams));
$statusCode = $response->getStatusCode();

if (500 <= $statusCode) {
    throw new ServerException($response);
}

if (400 <= $statusCode) {
    if (null !== $violations = $this->createConstraintViolationListFromResponse($response)) {
        throw new ResourceValidationException($resource, $violations);
    }

    throw new ClientException($response);
}

if (300 <= $statusCode) {
    throw new RedirectionException($response);
}
```

As you can see, we always enter in the first if, which will result in `ServerException`

**Comment by ismail1432** [comment]
I'm not convinced for "We may make it more readable" 

The same logic is used here => https://github.com/symfony/http-client/blob/5.3/Response/CommonResponseTrait.php#L172

**Comment by mtarld** [comment]
Closed thanks to https://github.com/mtarld/api-platform-ms-bundle/pull/69
