### ISSUE TITLE
Add retryable http client option

### ISSUE THREAD

**Issue by ismail1432** [mtarld/api-platform-ms-bundle#64]
Since Symfony 5.2 it's possible to add a [retrying strategy](https://symfony.com/blog/new-in-symfony-5-2-retryable-http-client) 
I'm wondering if we should add the same option or let the hand on "root" http client configuration used by the end user.

**Comment by art-cg** [comment]
@ismail1432 I am not sure about this feature. In my opinion the gloabl (root ) configuration is the better option. But it could be added to the docs of this repo to make developer aware of this retrying strategy.

**Comment by mtarld** [comment]
Yes indeed, as you can configure whatever HTTP client that will be used thanks to `api_platform_ms.http_client`, I don't think this feature is necessary.
We can effectively be more meaningful in our documentation by showing an example of a custom HTTP client configuration and injection. But IMHO we should not focus only on retry.

**Comment by mtarld** [comment]
Actually, it could be seen in:
- https://github.com/mtarld/api-platform-ms-bundle/blob/master/README.md (configuration)
- https://github.com/mtarld/api-platform-ms-bundle/blob/master/src/Resources/doc/tools/http-wrapper.md

I'm gonna close it, but feel free to open it again if you think it's still not enough :slightly_smiling_face:
